### PR TITLE
vault balance based discovery

### LINKED ISSUE #95: binary search should start at the vault balance not the total balance of the entire orderbook
## Motivation

more hops = more compute + logs + time

an order can never offer more than its vault balance so starting the search at the balance of the entire orderbook is wrong

## solution

start hops at the vault balance

### PR DESCRIPTION
**Pull request by rouzwelt**
## Motivation
resolves #95 

## Solution
get vault balance and use it as start value for binary search for `maximumInput` discovery

## Checks

By submitting this for review, I'm confirming I've done the following:
- [x] made this PR as small as possible
- [x] unit-tested any new functionality
- [x] linked any relevant issues or PRs

### CODE REVIEW

File: src/modes/srouter.js [hunk 1]
```diff
@@ -468,7 +474,7 @@ async function dryrun(
             if (bundledOrder.takeOrders.length === 0) {
                 hopAttrs["status"] = "all orders had lower ratio than market price";
                 hopsDetails[`details.hop-${j}`] = JSON.stringify(hopAttrs);
-                maximumInput = maximumInput.sub(obSellTokenBalance.div(2 ** j));
+                maximumInput = maximumInput.sub(vaultBalance.div(2 ** j));
```
Comment (thedavidmeister) [inline src/modes/srouter.js:477]: there are no tests that we actually use this value

**Review by thedavidmeister — CHANGES_REQUESTED** [review]

**Review by thedavidmeister — APPROVED** [review]

**Comment by thedavidmeister** [comment]
@rouzwelt this is approved but we need to discuss how to roll it out

**Review by thedavidmeister — CHANGES_REQUESTED** [review]
for some reason i don't seem to be getting calldata any more
