### PR TITLE
fix undefined txs otel error

### LINKED ISSUE #133: fix `Cannot destructure property 'txs' of '(intermediate value)' as it is undefined.`

### PR DESCRIPTION
**Pull request by rouzwelt**
## Motivation
fix `Cannot destructure property 'txs' of '(intermediate value)' as it is undefined.` error.
resolves #133 

## Solution
dont return undefined on early resolve when no orders are found but return correct object

## Checks

By submitting this for review, I'm confirming I've done the following:
- [x] made this PR as small as possible
- [ ] unit-tested any new functionality
- [x] linked any relevant issues or PRs

### CODE REVIEW

File: arb-bot.js [hunk 1]
```diff
@@ -293,13 +293,13 @@ const main = async argv => {
             const roundCtx = trace.setSpan(context.active(), roundSpan);
             options.rpc = rpcs[rpcTurn];
             try {
-                const { txs, foundOpp } = await arbRound(tracer, roundCtx, options, lastError);
-                if (txs && txs.length) {
+                const result = await arbRound(tracer, roundCtx, options, lastError);
```
Comment (thedavidmeister) [inline arb-bot.js:296]: is there a way to test the issue this is fixing?

**Review by thedavidmeister — CHANGES_REQUESTED** [review]

**Review by hardyjosh — APPROVED** [review]

**Review by hardyjosh — APPROVED** [review]
